version: '3.8'
services:
  billtitlesapi:
    build: .
#    image: docker.io/arihersh/billtitles:latest
    container_name: billtitleapi
    deploy:
      restart_policy:
        delay: 5s
#        max_attempts: 3
        window: 120s
    env_file:
      - .envrc
    ports:
      - "8008:8000"
    depends_on:
      - postgresql
    volumes:
      - .:/app
    command: [
        "uvicorn",
        "--reload",
        "--host", "0.0.0.0",
        "--port", "8000",
#        "-k", "uvicorn.workers.UvicornWorker",
        "billtitles.main:app"
    ]

  postgresql:
    image: docker.io/arihersh/billsim-pgsql:latest
    env_file:
      - .envrc
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  elastic_monitor:
    image: 'elastichq/elasticsearch-hq'
    ports:
      - '5005:5000'

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10000:8080"

volumes:
  pgdata:
  
#  data01:
#   driver: local
#
#  data02:
#   driver: local
#
#  data03:
#   driver: local
#networks:
#  elastic:
#    driver: bridge
# Exits with error:
# bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
# Set the vm.max_map_count kernel parameter to at least 262144
# Using podman, this worked:
# podman machine ssh
# sudo sysctl -w vm.max_map_count=262144
# exit 
# See https://stackoverflow.com/a/41251595/628748